### ISSUE TITLE
VGA scratch register is parsed incorrectly for large values

### ISSUE THREAD

**Issue by osenft** [jk-ozlabs/uart-render-controller#1]
In my use case, the the host's BIOS writes 0x3F0A00A8 into the VGA scratch register to activate the VGA:

```
root@aspeed:~# cat /sys/devices/platform/ahb/ahb:apb/1e6e2000.syscon/1e6e2000.syscon:scratch/vga0
1057620136
```

The decimal value is incorrectly parsed as 0x49.

**Comment by osenft** [comment]
From what I can tell, this is the result of the `buf` in `read_vga_pw_reg` being declared too small, as `char[8]`. 

Reasoning: We're reading a 32 bit register. The largest unsigned 32 bit number is 0xFFFFFFFF = 4294967295 (decimal). This requires 10 digits + `\0`. Therefore, `buf` should be declared `char[11]`.

**Comment by jk-ozlabs** [comment]
Fixed via https://github.com/jk-ozlabs/uart-render-controller/pull/2 . Thanks Oskar!
